name: Build CloudApp APK

on:
  workflow_dispatch:

concurrency:
  group: build-cloudapp
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip and install Briefcase
        run: |
          python -m pip install --upgrade pip
          pip install briefcase

      - name: Build Android APK with Briefcase
        run: |
          briefcase create android
          briefcase build android
          briefcase package android

      - name: Upload generated APK
        uses: actions/upload-artifact@v4
        with:
          name: CloudApp-APK
          path: "**/*.apk"
